//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationSearchApplicationAPI.Models
{
    using Microsoft.EntityFrameworkCore;
    using System;
    //using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;
    
    public partial class LocationSearchDatabaseEntities1 : DbContext
    {
        public LocationSearchDatabaseEntities1(DbContextOptions<LocationSearchDatabaseEntities1> options)
           : base(options)
        {
        }

        public LocationSearchDatabaseEntities1()
          //  : base("name=LocationSearchDatabaseEntities1")
        {
        }

        public DbSet<LocationImage> LocationImages { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Venue> Venues { get; set; }
    }
}
