//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationSearchApplicationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationImage
    {
        public int Id { get; set; }
        public string VenueId { get; set; }
        public string PhotoTitle { get; set; }
        public byte[] Image { get; set; }
        public string ImageId { get; set; }
    }
}
