//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationSearchApplicationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Dislike { get; set; }
        public string? Venueid { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> Like { get; set; }
        public string Name { get; set; }
        public byte[] Photos { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<bool> Restricted { get; set; }
        public string StoreId { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Verified { get; set; }

        public Guid UserId { get; set; }
        public string PlaceSearch { get; set; }
        public string PlaceSearchCategory { get; set; }
    }
}
